import type { Metadata } from "next";
import Link from "next/link";
import { GlassCard } from "@/components/shared/GlassCard";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "Terms of use for BillBrief",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">
          Terms &amp; Conditions
        </h1>
        <p className="text-muted-foreground mt-1">
          Last updated: 15 February 2025
        </p>
      </div>

      <GlassCard className="space-y-4">
        <h2 className="text-sm font-semibold">Acceptance of Terms</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          By accessing and using BillBrief, you agree to be bound by these
          Terms &amp; Conditions. If you do not agree with any part of these
          terms, please do not use the service.
        </p>
      </GlassCard>

      <GlassCard className="space-y-4">
        <h2 className="text-sm font-semibold">Description of Service</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          BillBrief is a free, open-source web application that provides
          AI-generated plain-English summaries of UK Parliamentary bills. The
          service allows you to browse bills, track legislation, receive push
          notifications for stage changes, and contact your Member of Parliament.
        </p>
      </GlassCard>

      <GlassCard className="space-y-4">
        <h2 className="text-sm font-semibold">AI-Generated Content</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Summaries and translations are generated by artificial intelligence
          (Claude AI by Anthropic) and are intended as simplified explanations
          to aid understanding. They are <strong>not</strong> legal advice and
          should not be relied upon as authoritative interpretations of
          legislation. Always refer to the official bill text on the{" "}
          <a
            href="https://bills.parliament.uk"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            UK Parliament website
          </a>{" "}
          for the definitive version.
        </p>
      </GlassCard>

      <GlassCard className="space-y-4">
        <h2 className="text-sm font-semibold">Parliamentary Data</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Bill data is sourced from the UK Parliament&apos;s public APIs. While
          we strive to keep information up to date, there may be delays between
          when Parliament publishes updates and when they appear in BillBrief.
          We do not guarantee the accuracy, completeness, or timeliness of the
          data displayed.
        </p>
      </GlassCard>

      <GlassCard className="space-y-4">
        <h2 className="text-sm font-semibold">Contact Your MP</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          The &ldquo;Contact Your MP&rdquo; feature uses the UK Parliament
          Members API to look up your representative by postcode. Email
          templates are provided as a starting point only. You are responsible
          for the content of any correspondence you send to your MP.
        </p>
      </GlassCard>

      <GlassCard className="space-y-4">
        <h2 className="text-sm font-semibold">No Account Required</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          BillBrief does not require account registration. Features such as
          bill tracking and push notifications use an anonymous device ID stored
          in your browser. You can clear this data at any time through your
          browser settings.
        </p>
      </GlassCard>

      <GlassCard className="space-y-4">
        <h2 className="text-sm font-semibold">Acceptable Use</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          You agree not to misuse the service, including but not limited to:
        </p>
        <ul className="space-y-2 text-sm text-muted-foreground">
          <li className="flex gap-2">
            <span className="text-primary shrink-0">&bull;</span>
            Automated scraping or excessive API requests
          </li>
          <li className="flex gap-2">
            <span className="text-primary shrink-0">&bull;</span>
            Attempting to disrupt or overload the service
          </li>
          <li className="flex gap-2">
            <span className="text-primary shrink-0">&bull;</span>
            Misrepresenting AI-generated summaries as official legal text
          </li>
        </ul>
      </GlassCard>

      <GlassCard className="space-y-4">
        <h2 className="text-sm font-semibold">Limitation of Liability</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          BillBrief is provided &ldquo;as is&rdquo; without warranty of any
          kind. To the fullest extent permitted by law, we disclaim all
          liability for any damages arising from your use of the service,
          including reliance on AI-generated summaries or parliamentary data.
        </p>
      </GlassCard>

      <GlassCard className="space-y-4">
        <h2 className="text-sm font-semibold">Changes to Terms</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          We may update these terms from time to time. Continued use of Bill
          Buddy after changes are published constitutes acceptance of the
          revised terms.
        </p>
      </GlassCard>

      <GlassCard className="space-y-4">
        <h2 className="text-sm font-semibold">Governing Law</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          These terms are governed by the laws of England and Wales.
        </p>
      </GlassCard>

      <p className="text-xs text-muted-foreground">
        See also:{" "}
        <Link href="/privacy" className="text-primary hover:underline">
          Privacy Policy
        </Link>
      </p>
    </div>
  );
}
